[theme]

# Used to style primary interface elements. It's the color displayed most frequently across your app's
# screens and components. Examples of widgets using this color are st.slider and st.checkbox.
primaryColor = "#b31b1b" #burgundy

# Background color for the main container.
backgroundColor = "#efefef" #argilegrey 

# Used as the background for most widgets. Examples of widgets with this background are st.sidebar,
# st.text_input, st.date_input.
secondaryBackgroundColor =  "#eaeaea" 

# Font color for the page.
textColor = "#333333" # black

# Font family (serif | sans serif | mono) for the page. Will not impact code areas.
# Default: "sans serif"
font = "sans serif"

[server]
headless = true
port = $PORT
enableCORS = false